apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cron
# namespace: prod
spec:
  schedule: "*/1 * * * *"   # runing cronjob for every 1 minute 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloworld
            image: busybox
            command: ["echo", "Kubernetes Job"]
          restartPolicy: OnFailure
