apiVersion: apps/v1
kind: Deployment
metadata:
 name: pyweb
 labels:
  app: webserver
 annotations:
  cause: "update to 1.13.10"
spec:
 replicas: 3
 selector:
  matchLabels:
    app: webserver
 strategy: 
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1
  type: RollingUpdate
 template:
  metadata:
   labels:
    app: webserver
  spec:
   containers:
   - name: pyweb
     image: nlpappu/myrepo:pyweb
     ports:
     - containerPort: 80
