apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
  app: webserver
 annotations:
  cause: "update to 1.7.9"
spec:
 replicas: 3
 selector:
  matchLabels:
   app: webserver
 strategy: 
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1
  type: RollingUpdate
 template:
  metadata:
   labels:
    app: webserver
  spec:
   containers:
   - name: nginx
     image: nginx@sha256:ed974981ec1a61206bb2d10d59a53d78cde38d0ff837421b458fd6f1eb82e476
     ports:
     - containerPort: 80
