apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Users\212616565\Downloads\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Users\212616565\Downloads\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: ""
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: 
      - name: redis-storage
        emptyDir: {}
status: {}
